name: Build Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.5.0'
        components: 'qt-tools qtnetworkauth'

    - name: Configure and build
      run: |
        qmake Olop.pro
        make

    - name: Compile
      run: make

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Built Application
        path: Olop.exe

    - name: Display artifact download link
      run: echo "Download the built application here: ${{ steps.artifacts.outputs.artifact_download_url }}"
